### PR TITLE
Add Phantom Knights AI.

### PR DESCRIPTION
**Pull request by SailTheWaterway**
Also updates Dragoon AI's name and list of AIs on readme.

### CODE REVIEW

**Comment by edo9300** [comment]
Please put the name changes in a separate pull request, also, you should add the executor to the libwindbot project as well.

**Comment by SailTheWaterway** [comment]
> Please put the name changes in a separate pull request, also, you should add the executor to the libwindbot project as well.

Name changes removed from pull request. Executor should already be compiled for libWindbot.cs

**Comment by TheFlameFlash** [comment]
tested the ai and encountered the following issues
[replay.zip](https://github.com/ProjectIgnis/windbot/files/8188030/replay.zip)

**Comment by SailTheWaterway** [comment]
> tested the ai and encountered the following issues [replay.zip](https://github.com/ProjectIgnis/windbot/files/8188030/replay.zip)

Thanks for bringing these to my attention. Yeah, I see what my mistakes were with most of these. I'll fix them shortly.

**Comment by SailTheWaterway** [comment]
Wrote this AI when I was new to both C# and was using an outdated PK build that has only aged worse. As a result, a lot of the decisions the bot makes are very peculiar, to put it one way.

**Pull request closed without merging**
