### PR TITLE
Fix summon loop with attempting to Tribute Summon

### PR DESCRIPTION
**Pull request by ScienceBall**
This fixes the issue with e.g. Horus LV6.

### CODE REVIEW

**Comment by ScienceBall** [comment]
If I just revert the change in 1bf1e57, then it will build libWindbot and not build Windbot. If you're saying that it should build both, then I can make a change so that it builds both projects.

**Comment by kevinlul** [comment]
My apologies, you are correct. It should build both projects. Otherwise this looks good to me!

**Comment by ScienceBall** [comment]
When I try to build libWindbot, I get the following build error:

The command "set E4K_OUTPUT="C:\Users\gcsjo\source\repos\windbot\output"
if exist %E4K_OUTPUT% rmdir /S /Q %E4K_OUTPUT%
"C:\Users\gcsjo\.nuget\packages\embeddinator-4000\0.4.0\tools\Embeddinator-4000.exe" "C:\Users\gcsjo\source\repos\windbot\bin\Debug\libWindbot.dll" --gen=Java --platform=Android --outdir=%E4K_OUTPUT% -c -v
" exited with code -532462766.

Should I still push the commit that makes Visual Studio build both projects?

**Comment by kevinlul** [comment]
Yes please. That's a problem with the libWindbot setup to convert into an Android aar.

**Pull request merged**
